# Generated by Django 2.2.12 on 2022-05-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SP', 'Sport Wear'), ('OW', 'Out Wear'), ('el', 'electronics'), ('d', 'drink'), ('su', 'school')], max_length=2),
        ),
    ]
