# Generated by Django 2.2.12 on 2022-05-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity_price',
            field=models.IntegerField(null=True),
        ),
    ]
