# Generated by Django 2.2.12 on 2022-05-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_cart_quantity_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity_price',
            new_name='totalamount',
        ),
    ]
