# Generated by Django 2.2.12 on 2022-05-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220519_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Shipping',
            field=models.IntegerField(null=True),
        ),
    ]
