# Generated by Django 4.0.4 on 2022-06-10 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='to_user',
        ),
        migrations.AddField(
            model_name='notification',
            name='from_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
