# Generated by Django 4.0.4 on 2022-06-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_notification_to_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.zone'),
        ),
    ]
