# Generated by Django 2.2.12 on 2022-05-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cart_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Shipping',
        ),
    ]
