# Generated by Django 4.0.4 on 2022-06-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_notification_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
