# Generated by Django 4.0.4 on 2022-06-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_package_purchase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Purchaseackage',
        ),
    ]
