# Generated by Django 4.0.4 on 2022-06-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_purchase_purchaseackage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchaseackage',
            new_name='Purchasepackage',
        ),
    ]
