# Generated by Django 4.0.4 on 2022-06-22 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_purchaseackage_purchasepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasepackage',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.package'),
        ),
    ]
